### ISSUE TITLE
Replace printing with a more robust logging library

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#20]
Excessive printing can be verbose for test output especially.  We should trim out the ones that don't feel necessary anymore.

For the ones that we want to keep because they are helpful for debugging, we should keep them but ideally we'd like to hide them from normal release builds / etc.  Therefore, it would likely be a good idea to adopt a logging library so we can turn off `debug` level logs when we want to https://github.com/gabime/spdlog

**Comment by doctashay** [comment]
We can associate this issue with #58 as the previous PR was closed

**Comment by doctashay** [comment]
Now that spdlog has been implemented in a basic way, we should look at expanding upon these logging features to assist with the process of debugging and running tests. We should do this by logging important information directly to a text file, generated and stored in the build directory. I think the sooner this is established, the better, as the project becomes more targeted for the end-user. 

Additionally, we should continue to adapt the project to use spdlog in other areas such as goalc and the decompiler. Currently it is only half-way implemented in the runtime. We should also review existing prints and decide if they can be removed entirely or moved to a debug context for the sake of brevity.

On a side-note, regarding prints coming from the GOAL compiler using functions such as Msg() - can these be adapted to utilize spdlog, or is that unsafe?

**Comment by water111** [comment]
I think we first need to figure out what we want each thing to print.  I'll start with the runtime and write up some notes about the decompiler/compiler tomorrow.

The runtime should ideally print very little and most things should just go to a file by default.  The `Msg` prints should only be in the runtime (specifically the kernel, as these came from the original game), and it would be okay to either change `Msg` to internally use spdlog or change `Msg` prints to use spdlog.  It would be nice if we could have a separate `Msg` log in either case.

I think the only dangerous thing that can happen with spdlog is if we create our own logger and don't use the multi-threaded version. See https://github.com/gabime/spdlog/wiki/1.1.-Thread-Safety.  Otherwise the messages shouldn't get scrambled.

Unless we are debugging the runtime itself, we'll be using the compiler to interact with the runtime, so I imagine the runtime will just run in the background and you won't look at it much.  I think there are a few things that we will want the runtime to print to the terminal always:
- A version number when it starts
- Whenever it resets itself (https://github.com/water111/jak-project/blob/master/game/runtime.cpp#L263)
- Error messages related to the listener starting up
- Some message saying that it has connected to the compiler (to avoid confusion if you run two runtimes at the same and accidentally connect to the wrong one)
- The "emergency" print mode from GOAL `format`: https://github.com/water111/jak-project/blob/master/game/kernel/kprint.cpp#L1057 In normal use this doesn't print anything but using `(format 0 ... ` from GOAL will allow you to print a message immediately before a crash occurs, or possibly while things are in a bad state and normal `format`s sent to the compiler won't work.


Some nice to have features:
- some command line flags for setting all log messages to be printed for easy debugging. We'd want to check for command line arguments here: https://github.com/water111/jak-project/blob/master/game/main.cpp#L11 then also make sure https://github.com/water111/jak-project/blob/master/game/kernel/kmachine.cpp#L59 ignores them, as the original GOAL "C Kernel" also looks at the command line arguments.

- A way to distinguish between our prints and prints that are in the original game. Right now it's hard to know without opening up Ghidra and checking the OVERLORD and C Kernel code.  Maybe there could even be a flag to enable only "original game prints" for the most authentic console log experience.

**Comment by water111** [comment]
thanks to @doctashay spdlog is now included and used for the runtime! https://github.com/water111/jak-project/pull/68
