### ISSUE TITLE
[Decompiler] Detect and flag risky VU vector instruction usage

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#262]
For VU instructions involving the `R` / `Q` / `I` or `ACC` registers, we have decided we will handle these elegantly in the decompiler just by wrapping the relevant instructions with `rlet`s (for example, initialize a vector with the constant register (I)'s values and use it as a normal operand for the instructions we've already added.

However, it's not long before you can start imagining issues that arise from misuse of these instructions.  For example, if the `ACC` value is used long-term (possibly across function calls) our solution may cease to be elegant.  Another example would be if the game runs-amuck on the constant register and modifies it.

As such, it would be nice if the decompiler could detect such situations so we could either re-evaluate our intended approach, or possibly handle it slightly differently.

**Comment by water111** [comment]
This is a good point, and I'll get started on this today.

My plan:
- Improve the warning system on the decompiler
- Make the vector instructions and registers work correctly with the register liveliness algorithm
- Add a check to see if any vector registers are live coming into a function, and flag these functions as "depends on value of vector registers when called"
- Count up how many times this happens and decide on a strategy.

**Comment by water111** [comment]
Some implementation notes:
To determine if a function depends on the value of a `vf` register, we want to see if there are any "live" `vf` registers at the entrance of the function.  A "live" register means that the value of the register _may_ be used.
A few examples:

Here, `vf2` is live at the start of the function because it is possible for the `.vadd` to read the value, if the condition in the `if` is false.
```
if (a < b) {
 vf2 = x;
}
(.vadd vf3 vf2 vf2)
```

Here, `vf2` is not live because its value at the beginning of the function can never be used
```
if (a < b) {
 vf2 = x;
} else {
  vf2 = y;
}
(.vadd vf3 vf2 vf2)
```

This approach is not 100% reliable, as it is possible to write code like:

```
if (condition1) {
  vf2 = x;
}

if (condition2) {
  vf2 = y;
}
(.vadd vf3 vf2 vf2)
````
where the programmer knows that at least one of `condition1` and `condition2` are true, but the compiler/decompiler does not. This will trigger a false positive that `vf2` is live at the beginning because the decompiler thinks that both conditions could be false.  I think this will be pretty rare, and there's not much we can do about it - even modern compilers have somewhat unreliable "this variable may be used uninitialized" errors for a similar reason.

The good news is this approach will never have a false negative, so we can't miss anything.


The analysis to determine a register is live is located in `reg_usage.cpp` (roughly https://www.cs.columbia.edu/~suman/secure_sw_devel/Basic_Program_Analysis_DF.pdf), and relies on instructions reporting which registers they read and write.

Previously, this only worked on registers which were either `gprs` (integers, pointers) or `fpr`s (single floating point), because these the original GOAL compiler only considered register liveliness for gprs/fprs. Everything with fprs was done manually by the programmers.

I enabled this `reg_usage` pass to work on `vf` registers as well, so the the register liveliness information will be correct for `vf` registers. But, I did not turn on later analysis passes for `vf`, like splitting registers into variables or analyzing types because these registers were only used in inline assembly and don't have types/variables associated with them.  We don't want fancy expression building/variable naming applied to these.

For example, consider:
```
(defun vector-float*! ((arg0 vector) (arg1 vector) (arg2 float))
  (.lqc2 vf1 0 arg1)
  (.qmtc2.i vf2 arg2)
  (.vaddx.w vf1 vf0 vf0)
  (.vmulx.xyz vf1 vf1 vf2)
  (.sqc2 vf1 0 arg0)
  arg0
  )
```
The register usage analysis tells us that the following registers are live:
```
a2 a0 vf0 a1
```
The `a0`, `a1`, and `a2` registers are used to pass function arguments, so this is expected.
The `vf0` register is the constant register, which is okay.

**Comment by water111** [comment]
This analysis ran on 10169 out of 10430 functions, and these were the functions that had bad dependencies:
- `matrix-4x4-inverse!` (false, type 1)
- `quaternion-negate!`  (false, type 2)
- `quaternion-inverse!` (false, type 2)
- `quaternion-conjugate!` (false, type 2)
- `vector-cos-rad!` (false, type 2)
- `vector-sincos-rad!` (false, type 2)
- `transform-float-point` **real!** (set up by `init-for-transform`?)
- `render-sky-tri` and `render-sky-quad` **real!** (set by `init-sky-regs`)
- `(method 20 collide-shape-prim)` **real!** (seems like `vf31` is an argument to this function)
- `sphere-cull` and `guard-band-cull` **real!** (seems like some camera stuff is always in `vf`'s, set up by `dma-add-process-drawable`)
- `render-ocean-quad` **real!** (set up by `init-ocean-far-regs`)
- `load-boundary` had some too (set up by `init-boundary-regs`)

The good news is that it's pretty rare and I was able to figure out how most of these work.  It's possible that the functions that weren't analyzed yet have more of these, but these are going to require some manual work anyway, so I'm not too worried.

## False type 1:
something like
```
vsub.w vf3, vf3, vf3 ;; sets w to zero
vadd.xyz vf3, vf1, vf2 ;; sets xyz
```

## False type 2
something like
```
vsub.xyzw vf2, vf2, vf2
```
