### ISSUE TITLE
[decompiler] process pointer `pp` type casts are lost in decompiled code if the type remains constant

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#676]
Despite adding type-casts, and the decompiler's type-cast being aware of them:
```asm
B0:
    lw v1, *camera*(s7)       ;; [  0] (set! v1-0 *camera*) [] -> [v1: camera-master ]
    beq s7, v1, L106          ;; [  1] (b! (not v1-0) L106 (nop!)) [v1: camera-master ] -> []
    sll r0, r0, 0

B1:
    lw v1, *camera*(s7)       ;; [  2] (set! v1-1 *camera*) [] -> [v1: camera-master ]
    lwu v1, 124(v1)           ;; [  3] (set! v1-2 (l.wu (+ v1-1 124))) [v1: camera-master ] -> [v1: uint ]
    sw v1, 2196(s6)           ;; [  4] (s.w! (+ pp 2196) v1-2) [v1: uint s6: camera-slave ] -> []
    lw v1, *camera*(s7)       ;; [  5] (set! v1-3 *camera*) [] -> [v1: camera-master ]
    lwu v1, 132(v1)           ;; [  6] (set! v1-4 (l.wu (+ v1-3 132))) [v1: camera-master ] -> [v1: uint ]
    sw v1, 2484(s6)           ;; [  7] (s.w! (+ pp 2484) v1-4) [v1: uint s6: camera-slave ] -> []
    beq r0, r0, L107          ;; [  8] (b! #t L107 (nop!)) [] -> []
    sll r0, r0, 0
```

```json
"cam-slave-init-vars": [
    [[0, 999], "s6", "camera-slave"]
  ],
```

The type-casts are dropped in the lisp output:
```lisp
(defun cam-slave-init-vars ()
  (with-pp (cond
            (*camera*
             (set! (-> pp options) (-> *camera* slave-options))
             (set! (-> pp change-event-from) (-> *camera* changer))
             )
            (else
             (set! (-> pp options) (the-as uint 0))
             (set! (-> pp change-event-from) (the-as uint #f))
             )
            )
```

There is a partial workaround, if you add a cast to make the type "change" throughout the course of the function, it will insert the casts:

```json
"cam-slave-init-vars": [
    [[0, 5], "s6", "process"],
    [[5, 999], "s6", "camera-slave"]
  ],
```

```lisp
(defun cam-slave-init-vars ()
  (with-pp (cond
            (*camera*
             (let ((v1-2 (-> *camera* slave-options)))
              (s.w! (+ pp 2196) v1-2)
              )
             (set!
              (-> (the-as camera-slave pp) change-event-from)
              (-> *camera* changer)
              )
             )
```

Unfortunately, this leaves out the very first usage of `pp`, but it fixes it for the rest of the function.  This seems to block successful decompilation of functions that use the process-pointer.

**Comment by water111** [comment]
This is the expected behavior with the way type casts work, but slightly unintuitive.  The `with-pp` thing is just a temporary workaround until we really support "behaviors" which are functions that expect `pp` to be a certain type.

Here's what's happening in your example.
- Every time `s6` register is accessed, the type casts say that the register contains a `camera-slave`
- Next, the decompiler picks a type for the `pp` variable. It always holds a `camera-slave`, so it picks `camera-slave`
- Nothing ever sets `pp` in the point of view of the decompiler.  It thinks you're using `pp` undefined, and it wants to insert a `(local-vars (pp camera-slave))` but the `with-pp` hack removes this.

Maybe I will work behaviors tomorrow because it seems like we're running into this a lot.

**Comment by water111** [comment]
https://github.com/water111/jak-project/pull/678 was close, but I forgot to have the type analysis pass override the type of the variable, so if you insert casts, it doesn't do the right thing.

**Comment by water111** [comment]
Also I forgot about the part where I tell the type analysis pass about this.
