### ISSUE TITLE
[decompiler] CFG cannot resolve in several `tfrag-methods` functions

### ISSUE THREAD

**Issue by xTVaser** [water111/jak-project#680]

**Comment by water111** [comment]
I took a quick look. The issue seems to be this segment of code every time:
```asm
    lw v1, *perf-stats*(s7)
    daddiu v1, v1, 272
    lwu a0, 28(v1)
    lwu a1, 4(v1)
    daddiu a1, a1, 1
    sw a1, 4(v1)
    beq a0, r0, L72
    sll r0, r0, 0

B7:
    mtc0 Perf, r0
    sync.l
    sync.p
    mtpc pcr0, r0
    mtpc pcr1, r0
    sync.l
    sync.p
    mtc0 Perf, a0
    sync.l
    sync.p
B8:
L72:
    or v1, r0, r0
 ```

the `beq a0, r0, L72` followed by a `nop` that's used in this way is not something that the GOAL compiler would output.  This was very likely an inline assembly branch.

Right now, the decompiler dies when it encounters an asm branch, but I'm working on handling this better here: https://github.com/water111/jak-project/pull/677
